-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 13:13:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maps` (
  `id` INT NOT NULL,
  `summoners rift` VARCHAR(45) NULL,
  `howling abyss` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players` (
  `id` INT NOT NULL,
  `player1` VARCHAR(45) NULL,
  `player2` VARCHAR(45) NULL,
  `player3` VARCHAR(45) NULL,
  `player4` VARCHAR(45) NULL,
  `player5` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`champions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`champions` (
  `id` INT NOT NULL,
  `ahri` VARCHAR(45) NULL,
  `jhin` VARCHAR(45) NULL,
  `gankplank` VARCHAR(45) NULL,
  `rammus` VARCHAR(45) NULL,
  `lilia` VARCHAR(45) NULL,
  `rek'sai` VARCHAR(45) NULL,
  `annie` VARCHAR(45) NULL,
  `leona` VARCHAR(45) NULL,
  `ashe` VARCHAR(45) NULL,
  `katarina` VARCHAR(45) NULL,
  `players_id` INT NOT NULL,
  `maps_id` INT NOT NULL,
  PRIMARY KEY (`id`, `players_id`, `maps_id`),
  INDEX `fk_champions_players1_idx` (`players_id` ASC) VISIBLE,
  INDEX `fk_champions_maps1_idx` (`maps_id` ASC) VISIBLE,
  CONSTRAINT `fk_champions_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_champions_maps1`
    FOREIGN KEY (`maps_id`)
    REFERENCES `mydb`.`maps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `id` INT NOT NULL,
  `long sword` VARCHAR(45) NULL,
  `doran's ring` VARCHAR(45) NULL,
  `dark seal` VARCHAR(45) NULL,
  `sickle` VARCHAR(45) NULL,
  `decaying potion` VARCHAR(45) NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`, `shop_id`),
  INDEX `fk_items_shop1_idx` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_shop1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`runes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`runes` (
  `id` INT NOT NULL,
  `precision` VARCHAR(45) NULL,
  `resolve` VARCHAR(45) NULL,
  `inspiration` VARCHAR(45) NULL,
  `socery` VARCHAR(45) NULL,
  `domination` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`champions_has_runes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`champions_has_runes` (
  `champions_id` INT NOT NULL,
  `runes_id` INT NOT NULL,
  PRIMARY KEY (`champions_id`, `runes_id`),
  INDEX `fk_champions_has_runes_runes1_idx` (`runes_id` ASC) VISIBLE,
  INDEX `fk_champions_has_runes_champions_idx` (`champions_id` ASC) VISIBLE,
  CONSTRAINT `fk_champions_has_runes_champions`
    FOREIGN KEY (`champions_id`)
    REFERENCES `mydb`.`champions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_champions_has_runes_runes1`
    FOREIGN KEY (`runes_id`)
    REFERENCES `mydb`.`runes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items_has_champions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items_has_champions` (
  `items_id` INT NOT NULL,
  `champions_id` INT NOT NULL,
  PRIMARY KEY (`items_id`, `champions_id`),
  INDEX `fk_items_has_champions_champions1_idx` (`champions_id` ASC) VISIBLE,
  INDEX `fk_items_has_champions_items1_idx` (`items_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_has_champions_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `mydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_has_champions_champions1`
    FOREIGN KEY (`champions_id`)
    REFERENCES `mydb`.`champions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
